### ISSUE TITLE
data upadtes

### ISSUE THREAD

**Issue by rivka-friedman** [microsoftgraph/msgraph-sample-github-connector-python#3]
is it possible to configure the connector to get updated if github data changes, i.e. a new repository is created?
I mean to incremental crawl

**Comment by jasonjoh** [comment]
@rivka-friedman this sample doesn't do that, but you could certainly build something like that. When a connector does a push is completely up to the developer. I could see using a [GitHub webhook](https://docs.github.com/en/webhooks) to listen for events, and then pushing new data into the connector.

Hope that helps!
