### ISSUE TITLE
ExternalItem with with a list property

### ISSUE THREAD

**Issue by rivka-friedman** [microsoftgraph/msgraph-sample-github-connector-python#4]
how should I create an ExternalItem with a list property?
I defined the Schema property as type=PropertyType.StringCollection:
                Property_(
                    name="collaborators",
                    type=PropertyType.StringCollection,
                    is_searchable=True,
                    is_retrievable=True,
                ),

how should this property be defined in the ExternalItem object?

            request_body = ExternalItem(
                id = repo["name"],
                acl=[
                    Acl(
                        type=AclType.Everyone,
                        value=repo["name"],
                        access_type=AccessType.Grant
                    )
                ],
                properties=Properties(
                    additional_data={
                        "collaborators": ['aaa','bbb']
                    }
                )

I think I need to use odata_type - but I don't see any documentation which data types are valid.
Could you please instruct which odata_type to use and to which object it should be added?

**Comment by jasonjoh** [comment]
Looking at https://learn.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-put-items?view=graph-rest-1.0&tabs=http, collections do require specifying the `odata.type`. I think this should get you going:

```python
properties = Properties(
    additional_data = {
        "collaborators@odata.type": "Collection(String)",
        "collaborators": ['aaa','bbb']
    }
)
```

**Comment by rivka-friedman** [comment]
that works. thanks a lot!

**Comment by rivka-friedman** [comment]
just want to understand - what is the odata_type property used for? I was mixed up and didn't find any documentation on it

**Comment by jasonjoh** [comment]
It's part of the OData specification - it's a way to specify the type of an object.

https://docs.oasis-open.org/odata/odata-json-format/v4.01/odata-json-format-v4.01.html#_Toc38457738
