### ISSUE TITLE
Custom connector icon in Copilot results

### ISSUE THREAD

**Issue by rivka-friedman** [microsoftgraph/msgraph-sample-github-connector-python#5]
I created my own custom connector and I see search results and copilot results includes data from my connector.
is it possible to configure the icon of the data source which is displayed in the bottom of the Microsoft Copilot 365 response, to display the repository name and include hyperlink to github repository URL?
See attached screenshot. Please advise.
Thanks in advance! 

[Screenshot 2024-05-23 at 23.04.39.pdf](https://github.com/microsoftgraph/msgraph-sample-github-connector-python/files/15422161/Screenshot.2024-05-23.at.23.04.39.pdf)

**Comment by jasonjoh** [comment]
@rivka-friedman this isn't the best forum to ask general questions about connectors - we reserve the issues in this repository to report issues with this specific sample.

With that said, yes this is possible, the .NET and TypeScript versions of this connector sample do this. You need to add [semantic labels](https://learn.microsoft.com/en-us/graph/connecting-external-content-manage-schema#semantic-labels) to properties in your schema that identify them as the icon and item URL.
